### ISSUE TITLE
占位${持证人} 文本替换无效，DocOperator  48 行有问题

### ISSUE THREAD

**Issue by zhaogituser** [xuhaojin/certificate-generator#11]

**Comment by xuhaojin** [comment]
是否能提供入参，以及使用的docx文件模板，如果想沟通详细信息，可以加我qq：1579582159，或者发邮件

**Comment by xuhaojin** [comment]
> _No description provided._

是否能提供入参，以及使用的docx文件模板，如果想沟通详细信息，可以加我qq：1579582159，或者发邮件
